// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/OCharnyshevich/minecraft-server/internal/gamedata"

type attributeRegistry struct {
	byName     map[string]gamedata.Attribute
	byResource map[string]gamedata.Attribute
	all        []gamedata.Attribute
}

func newAttributeRegistry() gamedata.AttributeRegistry {
	all := []gamedata.Attribute{
		{
			Name: "maxHealth",
			Resource: "generic.maxHealth",
			Default: 20,
			Min: 1,
			Max: 1024,
		},
		{
			Name: "followRange",
			Resource: "generic.followRange",
			Default: 32,
			Min: 0,
			Max: 2048,
		},
		{
			Name: "knockbackResistance",
			Resource: "generic.knockbackResistance",
			Default: 0,
			Min: 0,
			Max: 1,
		},
		{
			Name: "movementSpeed",
			Resource: "generic.movementSpeed",
			Default: 0.7,
			Min: 0,
			Max: 1024,
		},
		{
			Name: "attackDamage",
			Resource: "generic.attackDamage",
			Default: 2,
			Min: 0,
			Max: 2048,
		},
		{
			Name: "horseJumpStrength",
			Resource: "horse.jumpStrength",
			Default: 0.7,
			Min: 0,
			Max: 2,
		},
		{
			Name: "zombieSpawnReinforcements",
			Resource: "zombie.spawnReinforcements",
			Default: 0,
			Min: 0,
			Max: 1,
		},
		{
			Name: "attackSpeed",
			Resource: "generic.attackSpeed",
			Default: 4,
			Min: 0,
			Max: 1024,
		},
		{
			Name: "flyingSpeed",
			Resource: "generic.flyingSpeed",
			Default: 0.4,
			Min: 0,
			Max: 1024,
		},
		{
			Name: "attackKnockback",
			Resource: "generic.attackKnockback",
			Default: 0,
			Min: 0,
			Max: 5,
		},
		{
			Name: "armorHealth",
			Resource: "generic.armor",
			Default: 0,
			Min: 0,
			Max: 30,
		},
		{
			Name: "armorToughness",
			Resource: "generic.armorToughness",
			Default: 0,
			Min: 0,
			Max: 20,
		},
	}

	byName := make(map[string]gamedata.Attribute, len(all))
	byResource := make(map[string]gamedata.Attribute, len(all))
	for _, v := range all {
		byName[v.Name] = v
		byResource[v.Resource] = v
	}

	return &attributeRegistry{byName: byName, byResource: byResource, all: all}
}

func (r *attributeRegistry) ByName(name string) (gamedata.Attribute, bool)         { v, ok := r.byName[name]; return v, ok }
func (r *attributeRegistry) ByResource(resource string) (gamedata.Attribute, bool) { v, ok := r.byResource[resource]; return v, ok }
func (r *attributeRegistry) All() []gamedata.Attribute                             { return r.all }
