// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/OCharnyshevich/minecraft-server/internal/gamedata"

type materialRegistry struct {
	byName map[string]gamedata.Material
	all    []gamedata.Material
}

func newMaterialRegistry() gamedata.MaterialRegistry {
	all := []gamedata.Material{
		{
			Name: "dirt",
			ToolSpeeds: map[int]float64{
				256: 6,
				269: 2,
				273: 4,
				277: 8,
				284: 12,
			},
		},
		{
			Name: "leaves",
			ToolSpeeds: map[int]float64{
				267: 1.5,
				268: 1.5,
				272: 1.5,
				276: 1.5,
				283: 1.5,
				359: 6,
			},
		},
		{
			Name: "melon",
			ToolSpeeds: map[int]float64{
				267: 1.5,
				268: 1.5,
				272: 1.5,
				276: 1.5,
				283: 1.5,
			},
		},
		{
			Name: "plant",
			ToolSpeeds: map[int]float64{
				258: 6,
				267: 1.5,
				268: 1.5,
				271: 2,
				272: 1.5,
				275: 4,
				276: 1.5,
				279: 8,
				283: 1.5,
				286: 12,
			},
		},
		{
			Name: "rock",
			ToolSpeeds: map[int]float64{
				257: 6,
				270: 2,
				274: 4,
				278: 8,
				285: 12,
			},
		},
		{
			Name: "web",
			ToolSpeeds: map[int]float64{
				267: 15,
				268: 15,
				272: 15,
				276: 15,
				283: 15,
				359: 15,
			},
		},
		{
			Name: "wood",
			ToolSpeeds: map[int]float64{
				258: 6,
				271: 2,
				275: 4,
				279: 8,
				286: 12,
			},
		},
		{
			Name: "wool",
			ToolSpeeds: map[int]float64{
				359: 4.8,
			},
		},
	}

	byName := make(map[string]gamedata.Material, len(all))
	for _, v := range all {
		byName[v.Name] = v
	}

	return &materialRegistry{byName: byName, all: all}
}

func (r *materialRegistry) ByName(name string) (gamedata.Material, bool) {
	v, ok := r.byName[name]
	return v, ok
}
func (r *materialRegistry) All() []gamedata.Material { return r.all }
