// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

type AbilitiesCB struct {
	Flags int8 `mc:"i8"`
	FlyingSpeed float32 `mc:"f32"`
	WalkingSpeed float32 `mc:"f32"`
}

func (AbilitiesCB) PacketID() int32 { return 0x39 }

type AbilitiesSB struct {
	Flags int8 `mc:"i8"`
	FlyingSpeed float32 `mc:"f32"`
	WalkingSpeed float32 `mc:"f32"`
}

func (AbilitiesSB) PacketID() int32 { return 0x13 }

type Animation struct {
	EntityID int32 `mc:"varint"`
	Animation uint8 `mc:"u8"`
}

func (Animation) PacketID() int32 { return 0x0B }

type ArmAnimation struct{}

func (ArmAnimation) PacketID() int32 { return 0x0A }

type AttachEntity struct {
	EntityID int32 `mc:"i32"`
	VehicleID int32 `mc:"i32"`
	Leash bool `mc:"bool"`
}

func (AttachEntity) PacketID() int32 { return 0x1B }

type Bed struct {
	EntityID int32 `mc:"varint"`
	Location int64 `mc:"position"`
}

func (Bed) PacketID() int32 { return 0x0A }

type BlockAction struct {
	Location int64 `mc:"position"`
	Byte1 uint8 `mc:"u8"`
	Byte2 uint8 `mc:"u8"`
	BlockID int32 `mc:"varint"`
}

func (BlockAction) PacketID() int32 { return 0x24 }

type BlockBreakAnimation struct {
	EntityID int32 `mc:"varint"`
	Location int64 `mc:"position"`
	DestroyStage int8 `mc:"i8"`
}

func (BlockBreakAnimation) PacketID() int32 { return 0x25 }

type BlockChange struct {
	Location int64 `mc:"position"`
	Type int32 `mc:"varint"`
}

func (BlockChange) PacketID() int32 { return 0x23 }

type BlockDig struct {
	Status int32 `mc:"varint"`
	Location int64 `mc:"position"`
	Face int8 `mc:"i8"`
}

func (BlockDig) PacketID() int32 { return 0x07 }

type BlockPlace struct {
	Data []byte `mc:"rest"`
}

func (BlockPlace) PacketID() int32 { return 0x08 }

type Camera struct {
	CameraID int32 `mc:"varint"`
}

func (Camera) PacketID() int32 { return 0x43 }

type ChatCB struct {
	Message string `mc:"string"`
	Position int8 `mc:"i8"`
}

func (ChatCB) PacketID() int32 { return 0x02 }

type ChatSB struct {
	Message string `mc:"string"`
}

func (ChatSB) PacketID() int32 { return 0x01 }

type ClientCommand struct {
	Payload int32 `mc:"varint"`
}

func (ClientCommand) PacketID() int32 { return 0x16 }

type CloseWindowCB struct {
	WindowID uint8 `mc:"u8"`
}

func (CloseWindowCB) PacketID() int32 { return 0x2E }

type CloseWindowSB struct {
	WindowID uint8 `mc:"u8"`
}

func (CloseWindowSB) PacketID() int32 { return 0x0D }

type Collect struct {
	CollectedEntityID int32 `mc:"varint"`
	CollectorEntityID int32 `mc:"varint"`
}

func (Collect) PacketID() int32 { return 0x0D }

type CombatEvent struct {
	Data []byte `mc:"rest"`
}

func (CombatEvent) PacketID() int32 { return 0x42 }

type Compress struct {
	Threshold int32 `mc:"varint"`
}

func (Compress) PacketID() int32 { return 0x03 }

type CraftProgressBar struct {
	WindowID uint8 `mc:"u8"`
	Property int16 `mc:"i16"`
	Value int16 `mc:"i16"`
}

func (CraftProgressBar) PacketID() int32 { return 0x31 }

type CustomPayloadCB struct {
	Channel string `mc:"string"`
	Data []byte `mc:"rest"`
}

func (CustomPayloadCB) PacketID() int32 { return 0x3F }

type CustomPayloadSB struct {
	Channel string `mc:"string"`
	Data []byte `mc:"rest"`
}

func (CustomPayloadSB) PacketID() int32 { return 0x17 }

type Difficulty struct {
	Difficulty uint8 `mc:"u8"`
}

func (Difficulty) PacketID() int32 { return 0x41 }

type Disconnect struct {
	Reason string `mc:"string"`
}

func (Disconnect) PacketID() int32 { return 0x00 }

type EnchantItem struct {
	WindowID int8 `mc:"i8"`
	Enchantment int8 `mc:"i8"`
}

func (EnchantItem) PacketID() int32 { return 0x11 }

type EncryptionBeginCB struct {
	ServerID string `mc:"string"`
	PublicKey []byte `mc:"bytearray"`
	VerifyToken []byte `mc:"bytearray"`
}

func (EncryptionBeginCB) PacketID() int32 { return 0x01 }

type EncryptionBeginSB struct {
	SharedSecret []byte `mc:"bytearray"`
	VerifyToken []byte `mc:"bytearray"`
}

func (EncryptionBeginSB) PacketID() int32 { return 0x01 }

type Entity struct {
	EntityID int32 `mc:"varint"`
}

func (Entity) PacketID() int32 { return 0x14 }

type EntityAction struct {
	EntityID int32 `mc:"varint"`
	ActionID int32 `mc:"varint"`
	JumpBoost int32 `mc:"varint"`
}

func (EntityAction) PacketID() int32 { return 0x0B }

type EntityDestroy struct {
	Data []byte `mc:"rest"`
}

func (EntityDestroy) PacketID() int32 { return 0x13 }

type EntityEffect struct {
	EntityID int32 `mc:"varint"`
	EffectID int8 `mc:"i8"`
	Amplifier int8 `mc:"i8"`
	Duration int32 `mc:"varint"`
	HideParticles bool `mc:"bool"`
}

func (EntityEffect) PacketID() int32 { return 0x1D }

type EntityEquipment struct {
	Data []byte `mc:"rest"`
}

func (EntityEquipment) PacketID() int32 { return 0x04 }

type EntityHeadRotation struct {
	EntityID int32 `mc:"varint"`
	HeadYaw int8 `mc:"i8"`
}

func (EntityHeadRotation) PacketID() int32 { return 0x19 }

type EntityLook struct {
	EntityID int32 `mc:"varint"`
	Yaw int8 `mc:"i8"`
	Pitch int8 `mc:"i8"`
	OnGround bool `mc:"bool"`
}

func (EntityLook) PacketID() int32 { return 0x16 }

type EntityMetadata struct {
	Data []byte `mc:"rest"`
}

func (EntityMetadata) PacketID() int32 { return 0x1C }

type EntityMoveLook struct {
	EntityID int32 `mc:"varint"`
	DX int8 `mc:"i8"`
	DY int8 `mc:"i8"`
	DZ int8 `mc:"i8"`
	Yaw int8 `mc:"i8"`
	Pitch int8 `mc:"i8"`
	OnGround bool `mc:"bool"`
}

func (EntityMoveLook) PacketID() int32 { return 0x17 }

type EntityStatus struct {
	EntityID int32 `mc:"i32"`
	EntityStatus int8 `mc:"i8"`
}

func (EntityStatus) PacketID() int32 { return 0x1A }

type EntityTeleport struct {
	EntityID int32 `mc:"varint"`
	X int32 `mc:"i32"`
	Y int32 `mc:"i32"`
	Z int32 `mc:"i32"`
	Yaw int8 `mc:"i8"`
	Pitch int8 `mc:"i8"`
	OnGround bool `mc:"bool"`
}

func (EntityTeleport) PacketID() int32 { return 0x18 }

type EntityVelocity struct {
	EntityID int32 `mc:"varint"`
	VelocityX int16 `mc:"i16"`
	VelocityY int16 `mc:"i16"`
	VelocityZ int16 `mc:"i16"`
}

func (EntityVelocity) PacketID() int32 { return 0x12 }

type Experience struct {
	ExperienceBar float32 `mc:"f32"`
	Level int32 `mc:"varint"`
	TotalExperience int32 `mc:"varint"`
}

func (Experience) PacketID() int32 { return 0x1F }

type Explosion struct {
	Data []byte `mc:"rest"`
}

func (Explosion) PacketID() int32 { return 0x27 }

type Flying struct {
	OnGround bool `mc:"bool"`
}

func (Flying) PacketID() int32 { return 0x03 }

type GameStateChange struct {
	Reason uint8 `mc:"u8"`
	GameMode float32 `mc:"f32"`
}

func (GameStateChange) PacketID() int32 { return 0x2B }

type HeldItemSlotCB struct {
	Slot int8 `mc:"i8"`
}

func (HeldItemSlotCB) PacketID() int32 { return 0x09 }

type HeldItemSlotSB struct {
	SlotID int16 `mc:"i16"`
}

func (HeldItemSlotSB) PacketID() int32 { return 0x09 }

type KeepAliveCB struct {
	KeepAliveID int32 `mc:"varint"`
}

func (KeepAliveCB) PacketID() int32 { return 0x00 }

type KeepAliveSB struct {
	KeepAliveID int32 `mc:"varint"`
}

func (KeepAliveSB) PacketID() int32 { return 0x00 }

type KickDisconnect struct {
	Reason string `mc:"string"`
}

func (KickDisconnect) PacketID() int32 { return 0x40 }

type LegacyServerListPing struct {
	Payload uint8 `mc:"u8"`
}

func (LegacyServerListPing) PacketID() int32 { return 0xFE }

type Login struct {
	EntityID int32 `mc:"i32"`
	GameMode uint8 `mc:"u8"`
	Dimension int8 `mc:"i8"`
	Difficulty uint8 `mc:"u8"`
	MaxPlayers uint8 `mc:"u8"`
	LevelType string `mc:"string"`
	ReducedDebugInfo bool `mc:"bool"`
}

func (Login) PacketID() int32 { return 0x01 }

type LoginStart struct {
	Username string `mc:"string"`
}

func (LoginStart) PacketID() int32 { return 0x00 }

type Look struct {
	Yaw float32 `mc:"f32"`
	Pitch float32 `mc:"f32"`
	OnGround bool `mc:"bool"`
}

func (Look) PacketID() int32 { return 0x05 }

type Map struct {
	Data []byte `mc:"rest"`
}

func (Map) PacketID() int32 { return 0x34 }

type MapChunk struct {
	X int32 `mc:"i32"`
	Z int32 `mc:"i32"`
	GroundUp bool `mc:"bool"`
	BitMap uint16 `mc:"u16"`
	ChunkData []byte `mc:"bytearray"`
}

func (MapChunk) PacketID() int32 { return 0x21 }

type MapChunkBulk struct {
	Data []byte `mc:"rest"`
}

func (MapChunkBulk) PacketID() int32 { return 0x26 }

type MultiBlockChange struct {
	Data []byte `mc:"rest"`
}

func (MultiBlockChange) PacketID() int32 { return 0x22 }

type NamedEntitySpawn struct {
	Data []byte `mc:"rest"`
}

func (NamedEntitySpawn) PacketID() int32 { return 0x0C }

type NamedSoundEffect struct {
	SoundName string `mc:"string"`
	X int32 `mc:"i32"`
	Y int32 `mc:"i32"`
	Z int32 `mc:"i32"`
	Volume float32 `mc:"f32"`
	Pitch uint8 `mc:"u8"`
}

func (NamedSoundEffect) PacketID() int32 { return 0x29 }

type OpenSignEntity struct {
	Location int64 `mc:"position"`
}

func (OpenSignEntity) PacketID() int32 { return 0x36 }

type OpenWindow struct {
	Data []byte `mc:"rest"`
}

func (OpenWindow) PacketID() int32 { return 0x2D }

type PingCB struct {
	Time int64 `mc:"i64"`
}

func (PingCB) PacketID() int32 { return 0x01 }

type PingSB struct {
	Time int64 `mc:"i64"`
}

func (PingSB) PacketID() int32 { return 0x01 }

type PingStart struct{}

func (PingStart) PacketID() int32 { return 0x00 }

type PlayerInfo struct {
	Data []byte `mc:"rest"`
}

func (PlayerInfo) PacketID() int32 { return 0x38 }

type PlayerlistHeader struct {
	Header string `mc:"string"`
	Footer string `mc:"string"`
}

func (PlayerlistHeader) PacketID() int32 { return 0x47 }

type PositionCB struct {
	X float64 `mc:"f64"`
	Y float64 `mc:"f64"`
	Z float64 `mc:"f64"`
	Yaw float32 `mc:"f32"`
	Pitch float32 `mc:"f32"`
	Flags int8 `mc:"i8"`
}

func (PositionCB) PacketID() int32 { return 0x08 }

type PositionLook struct {
	X float64 `mc:"f64"`
	Y float64 `mc:"f64"`
	Z float64 `mc:"f64"`
	Yaw float32 `mc:"f32"`
	Pitch float32 `mc:"f32"`
	OnGround bool `mc:"bool"`
}

func (PositionLook) PacketID() int32 { return 0x06 }

type PositionSB struct {
	X float64 `mc:"f64"`
	Y float64 `mc:"f64"`
	Z float64 `mc:"f64"`
	OnGround bool `mc:"bool"`
}

func (PositionSB) PacketID() int32 { return 0x04 }

type RelEntityMove struct {
	EntityID int32 `mc:"varint"`
	DX int8 `mc:"i8"`
	DY int8 `mc:"i8"`
	DZ int8 `mc:"i8"`
	OnGround bool `mc:"bool"`
}

func (RelEntityMove) PacketID() int32 { return 0x15 }

type RemoveEntityEffect struct {
	EntityID int32 `mc:"varint"`
	EffectID int8 `mc:"i8"`
}

func (RemoveEntityEffect) PacketID() int32 { return 0x1E }

type ResourcePackReceive struct {
	Hash string `mc:"string"`
	Result int32 `mc:"varint"`
}

func (ResourcePackReceive) PacketID() int32 { return 0x19 }

type ResourcePackSend struct {
	URL string `mc:"string"`
	Hash string `mc:"string"`
}

func (ResourcePackSend) PacketID() int32 { return 0x48 }

type Respawn struct {
	Dimension int32 `mc:"i32"`
	Difficulty uint8 `mc:"u8"`
	Gamemode uint8 `mc:"u8"`
	LevelType string `mc:"string"`
}

func (Respawn) PacketID() int32 { return 0x07 }

type ScoreboardDisplayObjective struct {
	Position int8 `mc:"i8"`
	Name string `mc:"string"`
}

func (ScoreboardDisplayObjective) PacketID() int32 { return 0x3D }

type ScoreboardObjective struct {
	Data []byte `mc:"rest"`
}

func (ScoreboardObjective) PacketID() int32 { return 0x3B }

type ScoreboardScore struct {
	Data []byte `mc:"rest"`
}

func (ScoreboardScore) PacketID() int32 { return 0x3C }

type ScoreboardTeam struct {
	Data []byte `mc:"rest"`
}

func (ScoreboardTeam) PacketID() int32 { return 0x3E }

type ServerInfo struct {
	Response string `mc:"string"`
}

func (ServerInfo) PacketID() int32 { return 0x00 }

type SetCompression struct {
	Threshold int32 `mc:"varint"`
}

func (SetCompression) PacketID() int32 { return 0x46 }

type SetCreativeSlot struct {
	Data []byte `mc:"rest"`
}

func (SetCreativeSlot) PacketID() int32 { return 0x10 }

type SetProtocol struct {
	ProtocolVersion int32 `mc:"varint"`
	ServerHost string `mc:"string"`
	ServerPort uint16 `mc:"u16"`
	NextState int32 `mc:"varint"`
}

func (SetProtocol) PacketID() int32 { return 0x00 }

type SetSlot struct {
	Data []byte `mc:"rest"`
}

func (SetSlot) PacketID() int32 { return 0x2F }

type Settings struct {
	Locale string `mc:"string"`
	ViewDistance int8 `mc:"i8"`
	ChatFlags int8 `mc:"i8"`
	ChatColors bool `mc:"bool"`
	SkinParts uint8 `mc:"u8"`
}

func (Settings) PacketID() int32 { return 0x15 }

type SpawnEntity struct {
	Data []byte `mc:"rest"`
}

func (SpawnEntity) PacketID() int32 { return 0x0E }

type SpawnEntityExperienceOrb struct {
	EntityID int32 `mc:"varint"`
	X int32 `mc:"i32"`
	Y int32 `mc:"i32"`
	Z int32 `mc:"i32"`
	Count int16 `mc:"i16"`
}

func (SpawnEntityExperienceOrb) PacketID() int32 { return 0x11 }

type SpawnEntityLiving struct {
	Data []byte `mc:"rest"`
}

func (SpawnEntityLiving) PacketID() int32 { return 0x0F }

type SpawnEntityPainting struct {
	EntityID int32 `mc:"varint"`
	Title string `mc:"string"`
	Location int64 `mc:"position"`
	Direction uint8 `mc:"u8"`
}

func (SpawnEntityPainting) PacketID() int32 { return 0x10 }

type SpawnEntityWeather struct {
	EntityID int32 `mc:"varint"`
	Type int8 `mc:"i8"`
	X int32 `mc:"i32"`
	Y int32 `mc:"i32"`
	Z int32 `mc:"i32"`
}

func (SpawnEntityWeather) PacketID() int32 { return 0x2C }

type SpawnPosition struct {
	Location int64 `mc:"position"`
}

func (SpawnPosition) PacketID() int32 { return 0x05 }

type Spectate struct {
	Target [16]byte `mc:"uuid"`
}

func (Spectate) PacketID() int32 { return 0x18 }

type Statistics struct {
	Data []byte `mc:"rest"`
}

func (Statistics) PacketID() int32 { return 0x37 }

type SteerVehicle struct {
	Sideways float32 `mc:"f32"`
	Forward float32 `mc:"f32"`
	Jump uint8 `mc:"u8"`
}

func (SteerVehicle) PacketID() int32 { return 0x0C }

type Success struct {
	UUID string `mc:"string"`
	Username string `mc:"string"`
}

func (Success) PacketID() int32 { return 0x02 }

type TabCompleteCB struct {
	Data []byte `mc:"rest"`
}

func (TabCompleteCB) PacketID() int32 { return 0x3A }

type TabCompleteSB struct {
	Data []byte `mc:"rest"`
}

func (TabCompleteSB) PacketID() int32 { return 0x14 }

type TileEntityData struct {
	Data []byte `mc:"rest"`
}

func (TileEntityData) PacketID() int32 { return 0x35 }

type Title struct {
	Data []byte `mc:"rest"`
}

func (Title) PacketID() int32 { return 0x45 }

type TransactionCB struct {
	WindowID int8 `mc:"i8"`
	Action int16 `mc:"i16"`
	Accepted bool `mc:"bool"`
}

func (TransactionCB) PacketID() int32 { return 0x32 }

type TransactionSB struct {
	WindowID int8 `mc:"i8"`
	Action int16 `mc:"i16"`
	Accepted bool `mc:"bool"`
}

func (TransactionSB) PacketID() int32 { return 0x0F }

type UpdateAttributes struct {
	Data []byte `mc:"rest"`
}

func (UpdateAttributes) PacketID() int32 { return 0x20 }

type UpdateEntityNBT struct {
	Data []byte `mc:"rest"`
}

func (UpdateEntityNBT) PacketID() int32 { return 0x49 }

type UpdateHealth struct {
	Health float32 `mc:"f32"`
	Food int32 `mc:"varint"`
	FoodSaturation float32 `mc:"f32"`
}

func (UpdateHealth) PacketID() int32 { return 0x06 }

type UpdateSignCB struct {
	Location int64 `mc:"position"`
	Text1 string `mc:"string"`
	Text2 string `mc:"string"`
	Text3 string `mc:"string"`
	Text4 string `mc:"string"`
}

func (UpdateSignCB) PacketID() int32 { return 0x33 }

type UpdateSignSB struct {
	Location int64 `mc:"position"`
	Text1 string `mc:"string"`
	Text2 string `mc:"string"`
	Text3 string `mc:"string"`
	Text4 string `mc:"string"`
}

func (UpdateSignSB) PacketID() int32 { return 0x12 }

type UpdateTime struct {
	Age int64 `mc:"i64"`
	Time int64 `mc:"i64"`
}

func (UpdateTime) PacketID() int32 { return 0x03 }

type UseEntity struct {
	Data []byte `mc:"rest"`
}

func (UseEntity) PacketID() int32 { return 0x02 }

type WindowClick struct {
	Data []byte `mc:"rest"`
}

func (WindowClick) PacketID() int32 { return 0x0E }

type WindowItems struct {
	Data []byte `mc:"rest"`
}

func (WindowItems) PacketID() int32 { return 0x30 }

type WorldBorder struct {
	Data []byte `mc:"rest"`
}

func (WorldBorder) PacketID() int32 { return 0x44 }

type WorldEvent struct {
	EffectID int32 `mc:"i32"`
	Location int64 `mc:"position"`
	Data int32 `mc:"i32"`
	Global bool `mc:"bool"`
}

func (WorldEvent) PacketID() int32 { return 0x28 }

type WorldParticles struct {
	Data []byte `mc:"rest"`
}

func (WorldParticles) PacketID() int32 { return 0x2A }

