// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/OCharnyshevich/minecraft-server/internal/gamedata"

func newProtocol() *gamedata.Protocol {
	return &gamedata.Protocol{
		Types: map[string]string{
			"ByteArray": "complex",
			"UUID": "native",
			"array": "native",
			"bitfield": "native",
			"bitflags": "native",
			"bool": "native",
			"buffer": "native",
			"container": "native",
			"entityMetadata": "complex",
			"entityMetadataItem": "complex",
			"entityMetadataLoop": "native",
			"f32": "native",
			"f64": "native",
			"i16": "native",
			"i32": "native",
			"i64": "native",
			"i8": "native",
			"nbt": "native",
			"option": "native",
			"optionalNbt": "native",
			"position": "complex",
			"pstring": "native",
			"restBuffer": "native",
			"slot": "complex",
			"string": "complex",
			"switch": "native",
			"u16": "native",
			"u8": "native",
			"varint": "native",
			"varlong": "native",
			"void": "native",
		},
		Phases: map[string]gamedata.ProtocolPhase{
			"handshaking": {
				ToClient: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
					},
				},
				ToServer: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
						{
							Name: "set_protocol",
							ID: 0,
							Fields: []gamedata.PacketField{
								{Name: "protocolVersion", Type: "varint"},
								{Name: "serverHost", Type: "string"},
								{Name: "serverPort", Type: "u16"},
								{Name: "nextState", Type: "varint"},
							},
						},
						{
							Name: "legacy_server_list_ping",
							ID: 254,
							Fields: []gamedata.PacketField{
								{Name: "payload", Type: "u8"},
							},
						},
					},
				},
			},
			"status": {
				ToClient: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
						{
							Name: "server_info",
							ID: 0,
							Fields: []gamedata.PacketField{
								{Name: "response", Type: "string"},
							},
						},
						{
							Name: "ping",
							ID: 1,
							Fields: []gamedata.PacketField{
								{Name: "time", Type: "i64"},
							},
						},
					},
				},
				ToServer: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
						{
							Name: "ping_start",
							ID: 0,
							Fields: []gamedata.PacketField{
							},
						},
						{
							Name: "ping",
							ID: 1,
							Fields: []gamedata.PacketField{
								{Name: "time", Type: "i64"},
							},
						},
					},
				},
			},
			"login": {
				ToClient: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
						{
							Name: "disconnect",
							ID: 0,
							Fields: []gamedata.PacketField{
								{Name: "reason", Type: "string"},
							},
						},
						{
							Name: "encryption_begin",
							ID: 1,
							Fields: []gamedata.PacketField{
								{Name: "serverId", Type: "string"},
								{Name: "publicKey", Type: "ByteArray"},
								{Name: "verifyToken", Type: "ByteArray"},
							},
						},
						{
							Name: "success",
							ID: 2,
							Fields: []gamedata.PacketField{
								{Name: "uuid", Type: "string"},
								{Name: "username", Type: "string"},
							},
						},
						{
							Name: "compress",
							ID: 3,
							Fields: []gamedata.PacketField{
								{Name: "threshold", Type: "varint"},
							},
						},
					},
				},
				ToServer: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
						{
							Name: "login_start",
							ID: 0,
							Fields: []gamedata.PacketField{
								{Name: "username", Type: "string"},
							},
						},
						{
							Name: "encryption_begin",
							ID: 1,
							Fields: []gamedata.PacketField{
								{Name: "sharedSecret", Type: "ByteArray"},
								{Name: "verifyToken", Type: "ByteArray"},
							},
						},
					},
				},
			},
			"play": {
				ToClient: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
						{
							Name: "keep_alive",
							ID: 0,
							Fields: []gamedata.PacketField{
								{Name: "keepAliveId", Type: "varint"},
							},
						},
						{
							Name: "login",
							ID: 1,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "i32"},
								{Name: "gameMode", Type: "u8"},
								{Name: "dimension", Type: "i8"},
								{Name: "difficulty", Type: "u8"},
								{Name: "maxPlayers", Type: "u8"},
								{Name: "levelType", Type: "string"},
								{Name: "reducedDebugInfo", Type: "bool"},
							},
						},
						{
							Name: "chat",
							ID: 2,
							Fields: []gamedata.PacketField{
								{Name: "message", Type: "string"},
								{Name: "position", Type: "i8"},
							},
						},
						{
							Name: "update_time",
							ID: 3,
							Fields: []gamedata.PacketField{
								{Name: "age", Type: "i64"},
								{Name: "time", Type: "i64"},
							},
						},
						{
							Name: "entity_equipment",
							ID: 4,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "slot", Type: "i16"},
								{Name: "item", Type: "slot"},
							},
						},
						{
							Name: "spawn_position",
							ID: 5,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
							},
						},
						{
							Name: "update_health",
							ID: 6,
							Fields: []gamedata.PacketField{
								{Name: "health", Type: "f32"},
								{Name: "food", Type: "varint"},
								{Name: "foodSaturation", Type: "f32"},
							},
						},
						{
							Name: "respawn",
							ID: 7,
							Fields: []gamedata.PacketField{
								{Name: "dimension", Type: "i32"},
								{Name: "difficulty", Type: "u8"},
								{Name: "gamemode", Type: "u8"},
								{Name: "levelType", Type: "string"},
							},
						},
						{
							Name: "position",
							ID: 8,
							Fields: []gamedata.PacketField{
								{Name: "x", Type: "f64"},
								{Name: "y", Type: "f64"},
								{Name: "z", Type: "f64"},
								{Name: "yaw", Type: "f32"},
								{Name: "pitch", Type: "f32"},
								{Name: "flags", Type: "i8"},
							},
						},
						{
							Name: "held_item_slot",
							ID: 9,
							Fields: []gamedata.PacketField{
								{Name: "slot", Type: "i8"},
							},
						},
						{
							Name: "bed",
							ID: 10,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "location", Type: "position"},
							},
						},
						{
							Name: "animation",
							ID: 11,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "animation", Type: "u8"},
							},
						},
						{
							Name: "named_entity_spawn",
							ID: 12,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "playerUUID", Type: "UUID"},
								{Name: "x", Type: "i32"},
								{Name: "y", Type: "i32"},
								{Name: "z", Type: "i32"},
								{Name: "yaw", Type: "i8"},
								{Name: "pitch", Type: "i8"},
								{Name: "currentItem", Type: "i16"},
								{Name: "metadata", Type: "entityMetadata"},
							},
						},
						{
							Name: "collect",
							ID: 13,
							Fields: []gamedata.PacketField{
								{Name: "collectedEntityId", Type: "varint"},
								{Name: "collectorEntityId", Type: "varint"},
							},
						},
						{
							Name: "spawn_entity",
							ID: 14,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "type", Type: "i8"},
								{Name: "x", Type: "i32"},
								{Name: "y", Type: "i32"},
								{Name: "z", Type: "i32"},
								{Name: "pitch", Type: "i8"},
								{Name: "yaw", Type: "i8"},
								{Name: "intField", Type: "i32"},
								{Name: "objectData", Type: "complex"},
							},
						},
						{
							Name: "spawn_entity_living",
							ID: 15,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "type", Type: "u8"},
								{Name: "x", Type: "i32"},
								{Name: "y", Type: "i32"},
								{Name: "z", Type: "i32"},
								{Name: "yaw", Type: "i8"},
								{Name: "pitch", Type: "i8"},
								{Name: "headPitch", Type: "i8"},
								{Name: "velocityX", Type: "i16"},
								{Name: "velocityY", Type: "i16"},
								{Name: "velocityZ", Type: "i16"},
								{Name: "metadata", Type: "entityMetadata"},
							},
						},
						{
							Name: "spawn_entity_painting",
							ID: 16,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "title", Type: "string"},
								{Name: "location", Type: "position"},
								{Name: "direction", Type: "u8"},
							},
						},
						{
							Name: "spawn_entity_experience_orb",
							ID: 17,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "x", Type: "i32"},
								{Name: "y", Type: "i32"},
								{Name: "z", Type: "i32"},
								{Name: "count", Type: "i16"},
							},
						},
						{
							Name: "entity_velocity",
							ID: 18,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "velocityX", Type: "i16"},
								{Name: "velocityY", Type: "i16"},
								{Name: "velocityZ", Type: "i16"},
							},
						},
						{
							Name: "entity_destroy",
							ID: 19,
							Fields: []gamedata.PacketField{
								{Name: "entityIds", Type: "complex"},
							},
						},
						{
							Name: "entity",
							ID: 20,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
							},
						},
						{
							Name: "rel_entity_move",
							ID: 21,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "dX", Type: "i8"},
								{Name: "dY", Type: "i8"},
								{Name: "dZ", Type: "i8"},
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "entity_look",
							ID: 22,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "yaw", Type: "i8"},
								{Name: "pitch", Type: "i8"},
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "entity_move_look",
							ID: 23,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "dX", Type: "i8"},
								{Name: "dY", Type: "i8"},
								{Name: "dZ", Type: "i8"},
								{Name: "yaw", Type: "i8"},
								{Name: "pitch", Type: "i8"},
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "entity_teleport",
							ID: 24,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "x", Type: "i32"},
								{Name: "y", Type: "i32"},
								{Name: "z", Type: "i32"},
								{Name: "yaw", Type: "i8"},
								{Name: "pitch", Type: "i8"},
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "entity_head_rotation",
							ID: 25,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "headYaw", Type: "i8"},
							},
						},
						{
							Name: "entity_status",
							ID: 26,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "i32"},
								{Name: "entityStatus", Type: "i8"},
							},
						},
						{
							Name: "attach_entity",
							ID: 27,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "i32"},
								{Name: "vehicleId", Type: "i32"},
								{Name: "leash", Type: "bool"},
							},
						},
						{
							Name: "entity_metadata",
							ID: 28,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "metadata", Type: "entityMetadata"},
							},
						},
						{
							Name: "entity_effect",
							ID: 29,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "effectId", Type: "i8"},
								{Name: "amplifier", Type: "i8"},
								{Name: "duration", Type: "varint"},
								{Name: "hideParticles", Type: "bool"},
							},
						},
						{
							Name: "remove_entity_effect",
							ID: 30,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "effectId", Type: "i8"},
							},
						},
						{
							Name: "experience",
							ID: 31,
							Fields: []gamedata.PacketField{
								{Name: "experienceBar", Type: "f32"},
								{Name: "level", Type: "varint"},
								{Name: "totalExperience", Type: "varint"},
							},
						},
						{
							Name: "update_attributes",
							ID: 32,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "properties", Type: "complex"},
							},
						},
						{
							Name: "map_chunk",
							ID: 33,
							Fields: []gamedata.PacketField{
								{Name: "x", Type: "i32"},
								{Name: "z", Type: "i32"},
								{Name: "groundUp", Type: "bool"},
								{Name: "bitMap", Type: "u16"},
								{Name: "chunkData", Type: "ByteArray"},
							},
						},
						{
							Name: "multi_block_change",
							ID: 34,
							Fields: []gamedata.PacketField{
								{Name: "chunkX", Type: "i32"},
								{Name: "chunkZ", Type: "i32"},
								{Name: "records", Type: "complex"},
							},
						},
						{
							Name: "block_change",
							ID: 35,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
								{Name: "type", Type: "varint"},
							},
						},
						{
							Name: "block_action",
							ID: 36,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
								{Name: "byte1", Type: "u8"},
								{Name: "byte2", Type: "u8"},
								{Name: "blockId", Type: "varint"},
							},
						},
						{
							Name: "block_break_animation",
							ID: 37,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "location", Type: "position"},
								{Name: "destroyStage", Type: "i8"},
							},
						},
						{
							Name: "map_chunk_bulk",
							ID: 38,
							Fields: []gamedata.PacketField{
								{Name: "skyLightSent", Type: "bool"},
								{Name: "meta", Type: "complex"},
								{Name: "data", Type: "restBuffer"},
							},
						},
						{
							Name: "explosion",
							ID: 39,
							Fields: []gamedata.PacketField{
								{Name: "x", Type: "f32"},
								{Name: "y", Type: "f32"},
								{Name: "z", Type: "f32"},
								{Name: "radius", Type: "f32"},
								{Name: "affectedBlockOffsets", Type: "complex"},
								{Name: "playerMotionX", Type: "f32"},
								{Name: "playerMotionY", Type: "f32"},
								{Name: "playerMotionZ", Type: "f32"},
							},
						},
						{
							Name: "world_event",
							ID: 40,
							Fields: []gamedata.PacketField{
								{Name: "effectId", Type: "i32"},
								{Name: "location", Type: "position"},
								{Name: "data", Type: "i32"},
								{Name: "global", Type: "bool"},
							},
						},
						{
							Name: "named_sound_effect",
							ID: 41,
							Fields: []gamedata.PacketField{
								{Name: "soundName", Type: "string"},
								{Name: "x", Type: "i32"},
								{Name: "y", Type: "i32"},
								{Name: "z", Type: "i32"},
								{Name: "volume", Type: "f32"},
								{Name: "pitch", Type: "u8"},
							},
						},
						{
							Name: "world_particles",
							ID: 42,
							Fields: []gamedata.PacketField{
								{Name: "particleId", Type: "i32"},
								{Name: "longDistance", Type: "bool"},
								{Name: "x", Type: "f32"},
								{Name: "y", Type: "f32"},
								{Name: "z", Type: "f32"},
								{Name: "offsetX", Type: "f32"},
								{Name: "offsetY", Type: "f32"},
								{Name: "offsetZ", Type: "f32"},
								{Name: "particleData", Type: "f32"},
								{Name: "particles", Type: "i32"},
								{Name: "data", Type: "complex"},
							},
						},
						{
							Name: "game_state_change",
							ID: 43,
							Fields: []gamedata.PacketField{
								{Name: "reason", Type: "u8"},
								{Name: "gameMode", Type: "f32"},
							},
						},
						{
							Name: "spawn_entity_weather",
							ID: 44,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "type", Type: "i8"},
								{Name: "x", Type: "i32"},
								{Name: "y", Type: "i32"},
								{Name: "z", Type: "i32"},
							},
						},
						{
							Name: "open_window",
							ID: 45,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "u8"},
								{Name: "inventoryType", Type: "string"},
								{Name: "windowTitle", Type: "string"},
								{Name: "slotCount", Type: "u8"},
								{Name: "entityId", Type: "complex"},
							},
						},
						{
							Name: "close_window",
							ID: 46,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "u8"},
							},
						},
						{
							Name: "set_slot",
							ID: 47,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "i8"},
								{Name: "slot", Type: "i16"},
								{Name: "item", Type: "slot"},
							},
						},
						{
							Name: "window_items",
							ID: 48,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "u8"},
								{Name: "items", Type: "complex"},
							},
						},
						{
							Name: "craft_progress_bar",
							ID: 49,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "u8"},
								{Name: "property", Type: "i16"},
								{Name: "value", Type: "i16"},
							},
						},
						{
							Name: "transaction",
							ID: 50,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "i8"},
								{Name: "action", Type: "i16"},
								{Name: "accepted", Type: "bool"},
							},
						},
						{
							Name: "update_sign",
							ID: 51,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
								{Name: "text1", Type: "string"},
								{Name: "text2", Type: "string"},
								{Name: "text3", Type: "string"},
								{Name: "text4", Type: "string"},
							},
						},
						{
							Name: "map",
							ID: 52,
							Fields: []gamedata.PacketField{
								{Name: "itemDamage", Type: "varint"},
								{Name: "scale", Type: "i8"},
								{Name: "icons", Type: "complex"},
								{Name: "columns", Type: "i8"},
								{Name: "rows", Type: "complex"},
								{Name: "x", Type: "complex"},
								{Name: "y", Type: "complex"},
								{Name: "data", Type: "complex"},
							},
						},
						{
							Name: "tile_entity_data",
							ID: 53,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
								{Name: "action", Type: "u8"},
								{Name: "nbtData", Type: "optionalNbt"},
							},
						},
						{
							Name: "open_sign_entity",
							ID: 54,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
							},
						},
						{
							Name: "statistics",
							ID: 55,
							Fields: []gamedata.PacketField{
								{Name: "entries", Type: "complex"},
							},
						},
						{
							Name: "player_info",
							ID: 56,
							Fields: []gamedata.PacketField{
								{Name: "action", Type: "complex"},
								{Name: "data", Type: "complex"},
							},
						},
						{
							Name: "abilities",
							ID: 57,
							Fields: []gamedata.PacketField{
								{Name: "flags", Type: "i8"},
								{Name: "flyingSpeed", Type: "f32"},
								{Name: "walkingSpeed", Type: "f32"},
							},
						},
						{
							Name: "tab_complete",
							ID: 58,
							Fields: []gamedata.PacketField{
								{Name: "matches", Type: "complex"},
							},
						},
						{
							Name: "scoreboard_objective",
							ID: 59,
							Fields: []gamedata.PacketField{
								{Name: "name", Type: "string"},
								{Name: "action", Type: "i8"},
								{Name: "displayText", Type: "complex"},
								{Name: "type", Type: "complex"},
							},
						},
						{
							Name: "scoreboard_score",
							ID: 60,
							Fields: []gamedata.PacketField{
								{Name: "itemName", Type: "string"},
								{Name: "action", Type: "varint"},
								{Name: "scoreName", Type: "string"},
								{Name: "value", Type: "complex"},
							},
						},
						{
							Name: "scoreboard_display_objective",
							ID: 61,
							Fields: []gamedata.PacketField{
								{Name: "position", Type: "i8"},
								{Name: "name", Type: "string"},
							},
						},
						{
							Name: "scoreboard_team",
							ID: 62,
							Fields: []gamedata.PacketField{
								{Name: "team", Type: "string"},
								{Name: "mode", Type: "i8"},
								{Name: "name", Type: "complex"},
								{Name: "prefix", Type: "complex"},
								{Name: "suffix", Type: "complex"},
								{Name: "friendlyFire", Type: "complex"},
								{Name: "nameTagVisibility", Type: "complex"},
								{Name: "color", Type: "complex"},
								{Name: "players", Type: "complex"},
							},
						},
						{
							Name: "custom_payload",
							ID: 63,
							Fields: []gamedata.PacketField{
								{Name: "channel", Type: "string"},
								{Name: "data", Type: "restBuffer"},
							},
						},
						{
							Name: "kick_disconnect",
							ID: 64,
							Fields: []gamedata.PacketField{
								{Name: "reason", Type: "string"},
							},
						},
						{
							Name: "difficulty",
							ID: 65,
							Fields: []gamedata.PacketField{
								{Name: "difficulty", Type: "u8"},
							},
						},
						{
							Name: "combat_event",
							ID: 66,
							Fields: []gamedata.PacketField{
								{Name: "event", Type: "varint"},
								{Name: "duration", Type: "complex"},
								{Name: "playerId", Type: "complex"},
								{Name: "entityId", Type: "complex"},
								{Name: "message", Type: "complex"},
							},
						},
						{
							Name: "camera",
							ID: 67,
							Fields: []gamedata.PacketField{
								{Name: "cameraId", Type: "varint"},
							},
						},
						{
							Name: "world_border",
							ID: 68,
							Fields: []gamedata.PacketField{
								{Name: "action", Type: "varint"},
								{Name: "radius", Type: "complex"},
								{Name: "x", Type: "complex"},
								{Name: "z", Type: "complex"},
								{Name: "old_radius", Type: "complex"},
								{Name: "new_radius", Type: "complex"},
								{Name: "speed", Type: "complex"},
								{Name: "portalBoundary", Type: "complex"},
								{Name: "warning_time", Type: "complex"},
								{Name: "warning_blocks", Type: "complex"},
							},
						},
						{
							Name: "title",
							ID: 69,
							Fields: []gamedata.PacketField{
								{Name: "action", Type: "varint"},
								{Name: "text", Type: "complex"},
								{Name: "fadeIn", Type: "complex"},
								{Name: "stay", Type: "complex"},
								{Name: "fadeOut", Type: "complex"},
							},
						},
						{
							Name: "set_compression",
							ID: 70,
							Fields: []gamedata.PacketField{
								{Name: "threshold", Type: "varint"},
							},
						},
						{
							Name: "playerlist_header",
							ID: 71,
							Fields: []gamedata.PacketField{
								{Name: "header", Type: "string"},
								{Name: "footer", Type: "string"},
							},
						},
						{
							Name: "resource_pack_send",
							ID: 72,
							Fields: []gamedata.PacketField{
								{Name: "url", Type: "string"},
								{Name: "hash", Type: "string"},
							},
						},
						{
							Name: "update_entity_nbt",
							ID: 73,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "tag", Type: "nbt"},
							},
						},
					},
				},
				ToServer: gamedata.ProtocolDirection{
					Packets: []gamedata.Packet{
						{
							Name: "keep_alive",
							ID: 0,
							Fields: []gamedata.PacketField{
								{Name: "keepAliveId", Type: "varint"},
							},
						},
						{
							Name: "chat",
							ID: 1,
							Fields: []gamedata.PacketField{
								{Name: "message", Type: "string"},
							},
						},
						{
							Name: "use_entity",
							ID: 2,
							Fields: []gamedata.PacketField{
								{Name: "target", Type: "varint"},
								{Name: "mouse", Type: "varint"},
								{Name: "x", Type: "complex"},
								{Name: "y", Type: "complex"},
								{Name: "z", Type: "complex"},
							},
						},
						{
							Name: "flying",
							ID: 3,
							Fields: []gamedata.PacketField{
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "position",
							ID: 4,
							Fields: []gamedata.PacketField{
								{Name: "x", Type: "f64"},
								{Name: "y", Type: "f64"},
								{Name: "z", Type: "f64"},
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "look",
							ID: 5,
							Fields: []gamedata.PacketField{
								{Name: "yaw", Type: "f32"},
								{Name: "pitch", Type: "f32"},
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "position_look",
							ID: 6,
							Fields: []gamedata.PacketField{
								{Name: "x", Type: "f64"},
								{Name: "y", Type: "f64"},
								{Name: "z", Type: "f64"},
								{Name: "yaw", Type: "f32"},
								{Name: "pitch", Type: "f32"},
								{Name: "onGround", Type: "bool"},
							},
						},
						{
							Name: "block_dig",
							ID: 7,
							Fields: []gamedata.PacketField{
								{Name: "status", Type: "varint"},
								{Name: "location", Type: "position"},
								{Name: "face", Type: "i8"},
							},
						},
						{
							Name: "block_place",
							ID: 8,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
								{Name: "direction", Type: "i8"},
								{Name: "heldItem", Type: "slot"},
								{Name: "cursorX", Type: "i8"},
								{Name: "cursorY", Type: "i8"},
								{Name: "cursorZ", Type: "i8"},
							},
						},
						{
							Name: "held_item_slot",
							ID: 9,
							Fields: []gamedata.PacketField{
								{Name: "slotId", Type: "i16"},
							},
						},
						{
							Name: "arm_animation",
							ID: 10,
							Fields: []gamedata.PacketField{
							},
						},
						{
							Name: "entity_action",
							ID: 11,
							Fields: []gamedata.PacketField{
								{Name: "entityId", Type: "varint"},
								{Name: "actionId", Type: "varint"},
								{Name: "jumpBoost", Type: "varint"},
							},
						},
						{
							Name: "steer_vehicle",
							ID: 12,
							Fields: []gamedata.PacketField{
								{Name: "sideways", Type: "f32"},
								{Name: "forward", Type: "f32"},
								{Name: "jump", Type: "u8"},
							},
						},
						{
							Name: "close_window",
							ID: 13,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "u8"},
							},
						},
						{
							Name: "window_click",
							ID: 14,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "u8"},
								{Name: "slot", Type: "i16"},
								{Name: "mouseButton", Type: "i8"},
								{Name: "action", Type: "i16"},
								{Name: "mode", Type: "i8"},
								{Name: "item", Type: "slot"},
							},
						},
						{
							Name: "transaction",
							ID: 15,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "i8"},
								{Name: "action", Type: "i16"},
								{Name: "accepted", Type: "bool"},
							},
						},
						{
							Name: "set_creative_slot",
							ID: 16,
							Fields: []gamedata.PacketField{
								{Name: "slot", Type: "i16"},
								{Name: "item", Type: "slot"},
							},
						},
						{
							Name: "enchant_item",
							ID: 17,
							Fields: []gamedata.PacketField{
								{Name: "windowId", Type: "i8"},
								{Name: "enchantment", Type: "i8"},
							},
						},
						{
							Name: "update_sign",
							ID: 18,
							Fields: []gamedata.PacketField{
								{Name: "location", Type: "position"},
								{Name: "text1", Type: "string"},
								{Name: "text2", Type: "string"},
								{Name: "text3", Type: "string"},
								{Name: "text4", Type: "string"},
							},
						},
						{
							Name: "abilities",
							ID: 19,
							Fields: []gamedata.PacketField{
								{Name: "flags", Type: "i8"},
								{Name: "flyingSpeed", Type: "f32"},
								{Name: "walkingSpeed", Type: "f32"},
							},
						},
						{
							Name: "tab_complete",
							ID: 20,
							Fields: []gamedata.PacketField{
								{Name: "text", Type: "string"},
								{Name: "block", Type: "complex"},
							},
						},
						{
							Name: "settings",
							ID: 21,
							Fields: []gamedata.PacketField{
								{Name: "locale", Type: "string"},
								{Name: "viewDistance", Type: "i8"},
								{Name: "chatFlags", Type: "i8"},
								{Name: "chatColors", Type: "bool"},
								{Name: "skinParts", Type: "u8"},
							},
						},
						{
							Name: "client_command",
							ID: 22,
							Fields: []gamedata.PacketField{
								{Name: "payload", Type: "varint"},
							},
						},
						{
							Name: "custom_payload",
							ID: 23,
							Fields: []gamedata.PacketField{
								{Name: "channel", Type: "string"},
								{Name: "data", Type: "restBuffer"},
							},
						},
						{
							Name: "spectate",
							ID: 24,
							Fields: []gamedata.PacketField{
								{Name: "target", Type: "UUID"},
							},
						},
						{
							Name: "resource_pack_receive",
							ID: 25,
							Fields: []gamedata.PacketField{
								{Name: "hash", Type: "string"},
								{Name: "result", Type: "varint"},
							},
						},
					},
				},
			},
		},
	}
}
