// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/OCharnyshevich/minecraft-server/internal/gamedata"

func newVersion() *gamedata.Version {
	return &gamedata.Version{
		Protocol:         47,
		MinecraftVersion: "1.8.8",
		MajorVersion:     "1.8",
	}
}
