// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/go-theft-craft/server/pkg/gamedata"

type effectRegistry struct {
	byID   map[int]gamedata.Effect
	byName map[string]gamedata.Effect
	all    []gamedata.Effect
}

func newEffectRegistry() gamedata.EffectRegistry {
	all := []gamedata.Effect{
		{
			ID: 1,
			Name: "Speed",
			DisplayName: "Speed",
			Type: "good",
		},
		{
			ID: 2,
			Name: "Slowness",
			DisplayName: "Slowness",
			Type: "bad",
		},
		{
			ID: 3,
			Name: "Haste",
			DisplayName: "Haste",
			Type: "good",
		},
		{
			ID: 4,
			Name: "MiningFatigue",
			DisplayName: "Mining Fatigue",
			Type: "bad",
		},
		{
			ID: 5,
			Name: "Strength",
			DisplayName: "Strength",
			Type: "good",
		},
		{
			ID: 6,
			Name: "InstantHealth",
			DisplayName: "Instant Health",
			Type: "good",
		},
		{
			ID: 7,
			Name: "InstantDamage",
			DisplayName: "Instant Damage",
			Type: "bad",
		},
		{
			ID: 8,
			Name: "JumpBoost",
			DisplayName: "Jump Boost",
			Type: "good",
		},
		{
			ID: 9,
			Name: "Nausea",
			DisplayName: "Nausea",
			Type: "bad",
		},
		{
			ID: 10,
			Name: "Regeneration",
			DisplayName: "Regeneration",
			Type: "good",
		},
		{
			ID: 11,
			Name: "Resistance",
			DisplayName: "Resistance",
			Type: "good",
		},
		{
			ID: 12,
			Name: "FireResistance",
			DisplayName: "Fire Resistance",
			Type: "good",
		},
		{
			ID: 13,
			Name: "WaterBreathing",
			DisplayName: "Water Breathing",
			Type: "good",
		},
		{
			ID: 14,
			Name: "Invisibility",
			DisplayName: "Invisibility",
			Type: "good",
		},
		{
			ID: 15,
			Name: "Blindness",
			DisplayName: "Blindness",
			Type: "bad",
		},
		{
			ID: 16,
			Name: "NightVision",
			DisplayName: "Night Vision",
			Type: "good",
		},
		{
			ID: 17,
			Name: "Hunger",
			DisplayName: "Hunger",
			Type: "bad",
		},
		{
			ID: 18,
			Name: "Weakness",
			DisplayName: "Weakness",
			Type: "bad",
		},
		{
			ID: 19,
			Name: "Poison",
			DisplayName: "Poison",
			Type: "bad",
		},
		{
			ID: 20,
			Name: "Wither",
			DisplayName: "Wither",
			Type: "bad",
		},
		{
			ID: 21,
			Name: "HealthBoost",
			DisplayName: "Health Boost",
			Type: "good",
		},
		{
			ID: 22,
			Name: "Absorption",
			DisplayName: "Absorption",
			Type: "good",
		},
		{
			ID: 23,
			Name: "Saturation",
			DisplayName: "Saturation",
			Type: "good",
		},
	}

	byID := make(map[int]gamedata.Effect, len(all))
	byName := make(map[string]gamedata.Effect, len(all))
	for _, v := range all {
		byID[v.ID] = v
		byName[v.Name] = v
	}

	return &effectRegistry{byID: byID, byName: byName, all: all}
}

func (r *effectRegistry) ByID(id int) (gamedata.Effect, bool)       { v, ok := r.byID[id]; return v, ok }
func (r *effectRegistry) ByName(name string) (gamedata.Effect, bool) { v, ok := r.byName[name]; return v, ok }
func (r *effectRegistry) All() []gamedata.Effect                     { return r.all }
