// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/go-theft-craft/server/pkg/gamedata"

func init() {
	gamedata.Register("pc-1.8", New)
}

func New() *gamedata.GameData {
	return &gamedata.GameData{
		Blocks:          newBlockRegistry(),
		Items:           newItemRegistry(),
		Entities:        newEntityRegistry(),
		Biomes:          newBiomeRegistry(),
		Effects:         newEffectRegistry(),
		Enchantments:    newEnchantmentRegistry(),
		Foods:           newFoodRegistry(),
		Particles:       newParticleRegistry(),
		Instruments:     newInstrumentRegistry(),
		Attributes:      newAttributeRegistry(),
		Windows:         newWindowRegistry(),
		Materials:       newMaterialRegistry(),
		Recipes:         newRecipeRegistry(),
		Language:        newLanguageRegistry(),
		CollisionShapes: newCollisionShapes(),
		Protocol:        newProtocol(),
		Version:         newVersion(),
	}
}
