// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/go-theft-craft/server/pkg/gamedata"

type instrumentRegistry struct {
	byID   map[int]gamedata.Instrument
	byName map[string]gamedata.Instrument
	all    []gamedata.Instrument
}

func newInstrumentRegistry() gamedata.InstrumentRegistry {
	all := []gamedata.Instrument{
		{ID: 0, Name: "harp"},
		{ID: 1, Name: "doubleBass"},
		{ID: 2, Name: "snareDrum"},
		{ID: 3, Name: "sticks"},
		{ID: 4, Name: "bassDrum"},
	}

	byID := make(map[int]gamedata.Instrument, len(all))
	byName := make(map[string]gamedata.Instrument, len(all))
	for _, v := range all {
		byID[v.ID] = v
		byName[v.Name] = v
	}

	return &instrumentRegistry{byID: byID, byName: byName, all: all}
}

func (r *instrumentRegistry) ByID(id int) (gamedata.Instrument, bool) {
	v, ok := r.byID[id]
	return v, ok
}
func (r *instrumentRegistry) ByName(name string) (gamedata.Instrument, bool) {
	v, ok := r.byName[name]
	return v, ok
}
func (r *instrumentRegistry) All() []gamedata.Instrument { return r.all }
