// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/go-theft-craft/server/pkg/gamedata"

type particleRegistry struct {
	byID   map[int]gamedata.Particle
	byName map[string]gamedata.Particle
	all    []gamedata.Particle
}

func newParticleRegistry() gamedata.ParticleRegistry {
	all := []gamedata.Particle{
		{
			ID:   0,
			Name: "explode",
		},
		{
			ID:   1,
			Name: "largeexplode",
		},
		{
			ID:   2,
			Name: "hugeexplosion",
		},
		{
			ID:   3,
			Name: "fireworksSpark",
		},
		{
			ID:   4,
			Name: "bubble",
		},
		{
			ID:   5,
			Name: "splash",
		},
		{
			ID:   6,
			Name: "wake",
		},
		{
			ID:   7,
			Name: "suspended",
		},
		{
			ID:   8,
			Name: "depthsuspend",
		},
		{
			ID:   9,
			Name: "crit",
		},
		{
			ID:   10,
			Name: "magicCrit",
		},
		{
			ID:   11,
			Name: "smoke",
		},
		{
			ID:   12,
			Name: "largesmoke",
		},
		{
			ID:   13,
			Name: "spell",
		},
		{
			ID:   14,
			Name: "instantSpell",
		},
		{
			ID:   15,
			Name: "mobSpell",
		},
		{
			ID:   16,
			Name: "mobSpellAmbient",
		},
		{
			ID:   17,
			Name: "witchMagic",
		},
		{
			ID:   18,
			Name: "dripWater",
		},
		{
			ID:   19,
			Name: "dripLava",
		},
		{
			ID:   20,
			Name: "angryVillager",
		},
		{
			ID:   21,
			Name: "happyVillager",
		},
		{
			ID:   22,
			Name: "townaura",
		},
		{
			ID:   23,
			Name: "note",
		},
		{
			ID:   24,
			Name: "portal",
		},
		{
			ID:   25,
			Name: "enchantmenttable",
		},
		{
			ID:   26,
			Name: "flame",
		},
		{
			ID:   27,
			Name: "lava",
		},
		{
			ID:   28,
			Name: "footstep",
		},
		{
			ID:   29,
			Name: "cloud",
		},
		{
			ID:   30,
			Name: "reddust",
		},
		{
			ID:   31,
			Name: "snowballpoof",
		},
		{
			ID:   32,
			Name: "snowshovel",
		},
		{
			ID:   33,
			Name: "slime",
		},
		{
			ID:   34,
			Name: "heart",
		},
		{
			ID:   35,
			Name: "barrier",
		},
		{
			ID:   36,
			Name: "iconcrack_",
		},
		{
			ID:   37,
			Name: "blockcrack_",
		},
		{
			ID:   38,
			Name: "blockdust_",
		},
		{
			ID:   39,
			Name: "droplet",
		},
		{
			ID:   40,
			Name: "take",
		},
		{
			ID:   41,
			Name: "mobappearance",
		},
	}

	byID := make(map[int]gamedata.Particle, len(all))
	byName := make(map[string]gamedata.Particle, len(all))
	for _, v := range all {
		byID[v.ID] = v
		byName[v.Name] = v
	}

	return &particleRegistry{byID: byID, byName: byName, all: all}
}

func (r *particleRegistry) ByID(id int) (gamedata.Particle, bool) { v, ok := r.byID[id]; return v, ok }
func (r *particleRegistry) ByName(name string) (gamedata.Particle, bool) {
	v, ok := r.byName[name]
	return v, ok
}
func (r *particleRegistry) All() []gamedata.Particle { return r.all }
