// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/go-theft-craft/server/pkg/gamedata"

const (
	ProtocolVersion int32  = 47
	VersionName     string = "1.8.8"
	MetadataEnd     byte   = 0x7F
)

func newVersion() *gamedata.Version {
	return &gamedata.Version{
		Protocol:         47,
		MinecraftVersion: "1.8.8",
		MajorVersion:     "1.8",
	}
}
