// Code generated by cmd/codegen; DO NOT EDIT.
package pc_1_8

import "github.com/go-theft-craft/server/pkg/gamedata"

type windowRegistry struct {
	byID   map[string]gamedata.Window
	byName map[string]gamedata.Window
	all    []gamedata.Window
}

func newWindowRegistry() gamedata.WindowRegistry {
	all := []gamedata.Window{
		{
			ID:   "",
			Name: "Player",
			Slots: []gamedata.WindowSlot{
				{Name: "craft result", Index: 0, Size: 0},
				{Name: "craft grid", Index: 1, Size: 4},
				{Name: "armor", Index: 5, Size: 4},
				{Name: "helmet", Index: 5, Size: 0},
				{Name: "chestplate", Index: 6, Size: 0},
				{Name: "leggings", Index: 7, Size: 0},
				{Name: "boots", Index: 8, Size: 0},
			},
		},
		{
			ID:   "EntityHorse",
			Name: "Horse",
			Slots: []gamedata.WindowSlot{
				{Name: "saddle", Index: 0, Size: 0},
				{Name: "armor", Index: 1, Size: 0},
				{Name: "storage", Index: 2, Size: 15},
			},
			OpenedWith: []gamedata.WindowOpener{
				{Type: "entity", ID: 100},
			},
		},
		{
			ID:   "minecraft:anvil",
			Name: "Anvil",
			Slots: []gamedata.WindowSlot{
				{Name: "tool", Index: 0, Size: 0},
				{Name: "combined", Index: 1, Size: 0},
				{Name: "result", Index: 2, Size: 0},
			},
			Properties: []string{
				"repair cost",
			},
		},
		{
			ID:   "minecraft:beacon",
			Name: "Beacon",
			Slots: []gamedata.WindowSlot{
				{Name: "input", Index: 0, Size: 0},
			},
			Properties: []string{
				"level",
				"effect 1",
				"effect 2",
			},
			OpenedWith: []gamedata.WindowOpener{
				{Type: "block", ID: 138},
			},
		},
		{
			ID:   "minecraft:brewing_stand",
			Name: "Brewing Stand",
			Slots: []gamedata.WindowSlot{
				{Name: "ingredient", Index: 3, Size: 0},
				{Name: "result", Index: 0, Size: 3},
			},
			Properties: []string{
				"brew time",
			},
			OpenedWith: []gamedata.WindowOpener{
				{Type: "block", ID: 117},
			},
		},
		{
			ID:   "minecraft:chest",
			Name: "Chest",
		},
		{
			ID:   "minecraft:container",
			Name: "Container",
		},
		{
			ID:   "minecraft:crafting_table",
			Name: "Workbench",
			Slots: []gamedata.WindowSlot{
				{Name: "craft result", Index: 0, Size: 0},
				{Name: "craft grid", Index: 1, Size: 9},
			},
		},
		{
			ID:   "minecraft:dispenser",
			Name: "Dispenser",
		},
		{
			ID:   "minecraft:dropper",
			Name: "Dropper",
		},
		{
			ID:   "minecraft:enchanting_table",
			Name: "Enchantment Table",
			Slots: []gamedata.WindowSlot{
				{Name: "enchanted", Index: 0, Size: 0},
				{Name: "lapis", Index: 1, Size: 0},
			},
			Properties: []string{
				"xp 1",
				"xp 2",
				"xp 3",
				"seed",
				"tooltip 1",
				"tooltip 2",
				"tooltip 3",
			},
		},
		{
			ID:   "minecraft:furnace",
			Name: "Furnace",
			Slots: []gamedata.WindowSlot{
				{Name: "smelted", Index: 0, Size: 0},
				{Name: "fuel", Index: 1, Size: 0},
				{Name: "result", Index: 2, Size: 0},
			},
			Properties: []string{
				"fuel",
				"fuel max",
				"progress",
				"progress max",
			},
		},
		{
			ID:   "minecraft:hopper",
			Name: "Hopper",
		},
		{
			ID:   "minecraft:villager",
			Name: "NPC Trade",
			Slots: []gamedata.WindowSlot{
				{Name: "give 1", Index: 0, Size: 0},
				{Name: "give 2", Index: 1, Size: 0},
				{Name: "take", Index: 2, Size: 0},
			},
		},
	}

	byID := make(map[string]gamedata.Window, len(all))
	byName := make(map[string]gamedata.Window, len(all))
	for _, v := range all {
		byID[v.ID] = v
		byName[v.Name] = v
	}

	return &windowRegistry{byID: byID, byName: byName, all: all}
}

func (r *windowRegistry) ByID(id string) (gamedata.Window, bool) { v, ok := r.byID[id]; return v, ok }
func (r *windowRegistry) ByName(name string) (gamedata.Window, bool) {
	v, ok := r.byName[name]
	return v, ok
}
func (r *windowRegistry) All() []gamedata.Window { return r.all }
